export const KEY_DATA_QUESTIONS = "KEY_DATA_QUESTIONS";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";
export const GET_QUESTION = "GET_QUESTION";
export const BUY_HINT = "BUY_HINT";
export const SELECTED_QUESTION = "SELECTED_QUESTION";
export const GET_CURRENT_QUESTION = "GET_CURRENT_QUESTION";
